"""Add employee_meetings association table

Revision ID: 75cd9c5c991a
Revises: ce07466a91a7
Create Date: 2025-06-16 16:38:38.031809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75cd9c5c991a'
down_revision = 'ce07466a91a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_meetings',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_meetings_employee_id_employees')),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_employee_meetings_meeting_id_meetings')),
    sa.PrimaryKeyConstraint('employee_id', 'meeting_id')
    )
    op.drop_table('employees_meetings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees_meetings',
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('meeting_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='fk_employees_meetings_employee_id_employees'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name='fk_employees_meetings_meeting_id_meetings'),
    sa.PrimaryKeyConstraint('employee_id', 'meeting_id')
    )
    op.drop_table('employee_meetings')
    # ### end Alembic commands ###
